# Use postgres/example user/password credentials
version: "3.9"

services:
  pg:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?error enter password}
      POSTGRES_USER:  ${POSTGRES_USER?error}
      POSTGRES_HOST:  ${POSTGRES_HOST?error}
      POSTGRES_DATABASE:  ${POSTGRES_DATABASE?error}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
